# Generated by Django 2.1.7 on 2019-04-25 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batchrun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRunQueueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(db_index=True, verbose_name='scheduled run time')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='assignment time')),
                ('assignee_pid', models.IntegerField(blank=True, null=True, verbose_name='assignee process id (PID)')),
                ('scheduled_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batchrun.ScheduledJob', verbose_name='scheduled job')),
            ],
        ),
        migrations.AddField(
            model_name='jobrun',
            name='pid',
            field=models.IntegerField(blank=True, help_text='Records the process id of the process, which is/was executing this job', null=True, verbose_name='PID'),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='jobrunlogentry',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_entries', to='batchrun.JobRun', verbose_name='run'),
        ),
    ]
