# Generated by Django 2.1.7 on 2019-04-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchrun', '0002_auto_20190425_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrunlogentry',
            name='text',
        ),
        migrations.AddField(
            model_name='jobrunlogentry',
            name='data',
            field=models.BinaryField(blank=True, verbose_name='data'),
        ),
    ]
