# Generated by Django 2.1.7 on 2019-04-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchrun', '0003_auto_20190425_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrunlogentry',
            name='data',
        ),
        migrations.AddField(
            model_name='jobrunlogentry',
            name='text',
            field=models.TextField(blank=True, verbose_name='text'),
        ),
    ]
