# Generated by Django 2.2.13 on 2021-01-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchrun', '0003_logentry_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrunlogentry',
            options={'ordering': ('-run', 'time', 'id'), 'verbose_name': 'log entry', 'verbose_name_plural': 'log entries'},
        ),
        migrations.AddIndex(
            model_name='jobrunlogentry',
            index=models.Index(fields=['-run', 'time', 'id', 'kind'], name='batchrun_jo_run_id_b95597_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrunlogentry',
            index=models.Index(fields=['run', 'time', 'id', 'kind'], name='batchrun_jo_run_id_1364cb_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrunlogentry',
            index=models.Index(fields=['time', 'kind'], name='batchrun_jo_time_561a45_idx'),
        ),
    ]
