# Generated by Django 2.1.7 on 2019-04-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchrun', '0004_auto_20190429_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrunlogentry',
            name='line_number',
            field=models.IntegerField(default=0, verbose_name='line number'),
            preserve_default=False,
        ),
    ]
