# Generated by Django 2.1.7 on 2019-04-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchrun', '0005_jobrunlogentry_line_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrunlogentry',
            options={'ordering': ['run__started_at', 'run', 'time'], 'verbose_name': 'log entry of a job run', 'verbose_name_plural': 'log entries of job runs'},
        ),
        migrations.AlterField(
            model_name='jobrunlogentry',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='time'),
        ),
    ]
