# Generated by Django 2.1.7 on 2019-04-30 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchrun', '0007_auto_20190430_0516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrunqueueitem',
            options={'ordering': ['run_at']},
        ),
        migrations.RemoveField(
            model_name='jobrunqueueitem',
            name='created_at',
        ),
    ]
